import type { Metadata } from "next";
import { Cormorant_Garamond, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/atoms/Header/Header";
import Footer from "@/components/atoms/Footer/Footer";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant", 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${cormorant.variable} bg-[#F2F0EF] relative min-h-screen overflow-x-hidden flex flex-col`}>
          <Header />
          <div className="flex-1">
            {children}
          </div>
          <Footer />
      </body>
    </html>
  );
}
